# Generated by Django 2.2 on 2021-07-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_author_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
