# Generated by Django 2.2 on 2021-08-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
