# Generated by Django 2.2 on 2021-08-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0002_auto_20210812_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviewed_by',
        ),
    ]
