# Generated by Django 2.2 on 2021-08-02 22:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('TV_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.CheckConstraint(check=models.Q(release_date__lte=django.db.models.functions.datetime.Now()), name='release_date_cannot_be_in_future_dated'),
        ),
    ]
