# Generated by Django 2.2 on 2021-08-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20210804_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pw_hash',
            new_name='hash1',
        ),
    ]
