# Generated by Django 2.2 on 2021-08-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0003_auto_20210804_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hash1',
            new_name='password',
        ),
    ]
