# Generated by Django 2.2 on 2021-08-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_shows_app', '0002_auto_20210802_1525'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='show',
            name='release_date_cannot_be_in_future_dated',
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
