# Generated by Django 2.2 on 2021-08-20 17:25

import disney_collectibles_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney_collectibles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, validators=[disney_collectibles_app.models.email_validation]),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=100, validators=[disney_collectibles_app.models.validaeLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=100, validators=[disney_collectibles_app.models.validaeLengthGreaterThanTwo]),
        ),
    ]
